import "dotenv/config";
const num=(key:string,fallback:number)=>{const v=Number(process.env[key]);return Number.isFinite(v)?v:fallback};
const bool=(key:string,fallback:boolean)=>{const v=process.env[key];if(v==null)return fallback;return ["1","true","yes","on"].includes(v.toLowerCase())};
export const config={
  birdeyeApiKey:process.env.BIRDEYE_API_KEY??"", birdeyeMinIntervalMs:num("BIRDEYE_MIN_INTERVAL_MS",1100), birdeyeSnapshotCacheMs:num("BIRDEYE_SNAPSHOT_CACHE_MS",90000), birdeyeDeepCandidates:num("BIRDEYE_DEEP_CANDIDATES",5), birdeyeDeepMinScore:num("BIRDEYE_DEEP_MIN_SCORE",45), birdeyeHolderCandidates:num("BIRDEYE_HOLDER_CANDIDATES",3), birdeyeHolderMinScore:num("BIRDEYE_HOLDER_MIN_SCORE",65), birdeyeHolderCacheMs:num("BIRDEYE_HOLDER_CACHE_MS",300000), birdeyeCuBudgetPerHour:num("BIRDEYE_CU_BUDGET_PER_HOUR",1800), birdeyeCuCooldownMs:num("BIRDEYE_CU_COOLDOWN_MS",21600000), birdeyeNewIntervalMs:num("BIRDEYE_NEW_INTERVAL_MS",300000), birdeyeTrendingIntervalMs:num("BIRDEYE_TRENDING_INTERVAL_MS",120000), birdeyeMemeIntervalMs:num("BIRDEYE_MEME_INTERVAL_MS",0),
  heliusApiKey:process.env.HELIUS_API_KEY??"", riskDeepCandidates:num("RISK_DEEP_CANDIDATES",4), riskDeepMinScore:num("RISK_DEEP_MIN_SCORE",72), launchWindowSeconds:num("LAUNCH_WINDOW_SECONDS",180), launchTxLimit:num("LAUNCH_TX_LIMIT",100), clusterWalletThreshold:num("CLUSTER_WALLET_THRESHOLD",4), clusterRepeatThreshold:num("CLUSTER_REPEAT_THRESHOLD",3), maxFundingWalletChecks:num("MAX_FUNDING_WALLET_CHECKS",8), fundingHistoryLimit:num("FUNDING_HISTORY_LIMIT",30), fundingLookbackSeconds:num("FUNDING_LOOKBACK_SECONDS",86400), sharedFunderHighWallets:num("SHARED_FUNDER_HIGH_WALLETS",4), bundleSupplyMediumPct:num("BUNDLE_SUPPLY_MEDIUM_PCT",12), bundleSupplyHighPct:num("BUNDLE_SUPPLY_HIGH_PCT",25), crowdedSlotsHigh:num("CROWDED_SLOTS_HIGH",3), minLaunchTxForConfidence:num("MIN_LAUNCH_TX_FOR_CONFIDENCE",8), blockLowBundleConfidence:bool("BLOCK_LOW_BUNDLE_CONFIDENCE",true), holderTop1MediumPct:num("HOLDER_TOP1_MEDIUM_PCT",12), holderTop1HighPct:num("HOLDER_TOP1_HIGH_PCT",20), holderTop5MediumPct:num("HOLDER_TOP5_MEDIUM_PCT",35), holderTop5HighPct:num("HOLDER_TOP5_HIGH_PCT",50), holderTop10MediumPct:num("HOLDER_TOP10_MEDIUM_PCT",50), holderTop10HighPct:num("HOLDER_TOP10_HIGH_PCT",65), safetyTimeoutMs:num("SAFETY_TIMEOUT_MS",3500), safetyCacheMs:num("SAFETY_CACHE_MS",90000), safetyPrecheckCandidates:num("SAFETY_PRECHECK_CANDIDATES",12), paperFastSafety:bool("PAPER_FAST_SAFETY",true), paperMinObservationMs:num("PAPER_MIN_OBSERVATION_MS",10000), paperMinDataConfidence:num("PAPER_MIN_DATA_CONFIDENCE",60),
  mobulaApiKey:process.env.MOBULA_API_KEY??"", mobulaPulseUrl:process.env.MOBULA_PULSE_URL??"https://api.mobula.io/api/2/pulse", mobulaTrendingIntervalMs:num("MOBULA_TRENDING_INTERVAL_MS",15000), mobulaTimeoutMs:num("MOBULA_TIMEOUT_MS",8000), mobulaTrendingLimit:num("MOBULA_TRENDING_LIMIT",50), mobulaActiveSlots:num("MOBULA_ACTIVE_SLOTS",20), mobulaMinVolume1hUsd:num("MOBULA_MIN_VOLUME_1H_USD",5000), mobulaMinLiquidityUsd:num("MOBULA_MIN_LIQUIDITY_USD",1500), mobulaMinPriceChange1hPct:num("MOBULA_MIN_PRICE_CHANGE_1H_PCT",5),
  jupiterApiKey:process.env.JUPITER_API_KEY??"", jupiterMinIntervalMs:num("JUPITER_MIN_INTERVAL_MS",500), jupiterMaxRetries:num("JUPITER_MAX_RETRIES",2), requireSellRoute:bool("REQUIRE_SELL_ROUTE",true),
  ntfyServer:process.env.NTFY_SERVER??"https://ntfy.sh", ntfyTopic:process.env.NTFY_TOPIC??"", ntfyToken:process.env.NTFY_TOKEN??"", ntfyTimeoutMs:num("NTFY_TIMEOUT_MS",5000),
  emailReportsEnabled:bool("EMAIL_REPORT_ENABLED",false), reportEmail:process.env.REPORT_EMAIL??"", resendApiKey:process.env.RESEND_API_KEY??"", reportFrom:process.env.REPORT_FROM??"Broke Dog Bot <onboarding@resend.dev>", reportIntervalMs:num("REPORT_INTERVAL_MINUTES",60)*60000, reportTimezone:process.env.REPORT_TIMEZONE??"America/Denver", hourlyPaperReport:bool("HOURLY_PAPER_REPORT",true), hourlyLiveReport:bool("HOURLY_LIVE_REPORT",true), dailyEmailReport:bool("DAILY_EMAIL_REPORT",true),
  dexCacheMs:num("DEX_CACHE_MS",30000), dexTimeoutMs:num("DEX_TIMEOUT_MS",6000), dexDiscoveryIntervalMs:num("DEX_DISCOVERY_INTERVAL_MS",60000), dexMinIntervalMs:num("DEX_MIN_INTERVAL_MS",1200), dexRateLimitBackoffMs:num("DEX_RATE_LIMIT_BACKOFF_MS",90000), minActiveCandidates:num("MIN_ACTIVE_CANDIDATES",10), rewatchCooldownMs:num("REWATCH_COOLDOWN_MS",60000), knownRetentionMs:num("KNOWN_RETENTION_MS",1800000), trendingRewatchCooldownMs:num("TRENDING_REWATCH_COOLDOWN_MS",15000), momentumMinBuys5m:num("MOMENTUM_MIN_BUYS_5M",20), momentumMinBuySellRatio:num("MOMENTUM_MIN_BUY_SELL_RATIO",1.35), momentumMinPrice5mPct:num("MOMENTUM_MIN_PRICE_5M_PCT",5), routeDeepCandidates:num("ROUTE_DEEP_CANDIDATES",5), bundleDeepCandidates:num("BUNDLE_DEEP_CANDIDATES",3),
  rpcUrl:process.env.SOLANA_RPC_URL??"https://api.mainnet-beta.solana.com", privateKey:process.env.BS58_PRIVATE_KEY??"", liveTrading:bool("LIVE_TRADING",false), discoveryIntervalMs:num("DISCOVERY_INTERVAL_MS",15000),
  dogBrainEnabled:bool("DOG_BRAIN_ENABLED",true), dogBrainFile:process.env.DOG_BRAIN_FILE??"broke-dog-brain-v1.json", dogBrainMinSamples:num("DOG_BRAIN_MIN_SAMPLES",20), dogBrainLearnRate:num("DOG_BRAIN_LEARN_RATE",0.25), dogBrainMaxDailyWeightMove:num("DOG_BRAIN_MAX_DAILY_WEIGHT_MOVE",5), dogBrainMaxFeatureWeight:num("DOG_BRAIN_MAX_FEATURE_WEIGHT",5), dogBrainMaxScoreAdjustment:num("DOG_BRAIN_MAX_SCORE_ADJUSTMENT",8), dogBrainMaxRecords:num("DOG_BRAIN_MAX_RECORDS",2500), dogBrainRunnerPct:num("DOG_BRAIN_RUNNER_PCT",25), dogBrainRugPct:num("DOG_BRAIN_RUG_PCT",40), dogBrainReportIntervalMs:num("DOG_BRAIN_REPORT_INTERVAL_MS",86400000), dogBrainRollbackWindow:num("DOG_BRAIN_ROLLBACK_WINDOW",20), dogBrainRollbackDropPct:num("DOG_BRAIN_ROLLBACK_DROP_PCT",8),
  paperStartBalanceUsd:num("PAPER_START_BALANCE_USD",1000), paperNormalMaxUsd:num("PAPER_NORMAL_MAX_USD",45), paperEliteMaxUsd:num("PAPER_ELITE_MAX_USD",55), paperFlameMaxUsd:num("PAPER_FLAME_MAX_USD",70), paperTrackFees:bool("PAPER_TRACK_FEES",true), paperTrackSlippage:bool("PAPER_TRACK_SLIPPAGE",true), paperFeePct:num("PAPER_FEE_PCT",0.35), paperSlippagePct:num("PAPER_SLIPPAGE_PCT",0.65), paperWalletLogIntervalMs:num("PAPER_WALLET_LOG_INTERVAL_MS",15000), paperLedgerFile:process.env.PAPER_LEDGER_FILE??"broke-dog-paper-ledger.json", observationTickMs:num("OBSERVATION_TICK_MS",10000), minObservationMs:num("MIN_OBSERVATION_MS",30000), maxObservationMs:num("MAX_OBSERVATION_MS",120000), maxActiveCandidates:num("MAX_ACTIVE_CANDIDATES",36), freshCandidatesPerCycle:num("FRESH_CANDIDATES_PER_CYCLE",18), staleEvictScore:num("STALE_EVICT_SCORE",50), staleEvictAgeMs:num("STALE_EVICT_AGE_MS",90000), promoteScore:num("PROMOTE_SCORE",60), buyScore:num("BUY_SCORE",75), eliteScore:num("ELITE_SCORE",90), minDataConfidence:num("MIN_DATA_CONFIDENCE",72),
  flameEnabled:bool("FLAME_ENABLED",true), flameMinScore:num("FLAME_MIN_SCORE",92), flameMinRunnerScore:num("FLAME_MIN_RUNNER_SCORE",90), flameMinConfidence:num("FLAME_MIN_CONFIDENCE",85), flameMinSources:num("FLAME_MIN_SOURCES",2), flameMinBuySellRatio:num("FLAME_MIN_BUY_SELL_RATIO",3), flameMinVolume1mUsd:num("FLAME_MIN_VOLUME_1M_USD",1000), flameMaxAgeMin:num("FLAME_MAX_AGE_MIN",10),
  maxOpenPositions:num("MAX_OPEN_POSITIONS",2), thirdPositionScore:num("THIRD_POSITION_SCORE",90), maxPositionWalletPct:num("MAX_POSITION_WALLET_PCT",30), thirdPositionWalletPct:num("THIRD_POSITION_WALLET_PCT",20), minPositionUsd:num("MIN_POSITION_USD",2), solFeeReserve:num("SOL_FEE_RESERVE",0.015), maxDailyLossUsd:num("MAX_DAILY_LOSS_USD",5),
  solUsdCacheMs:num("SOL_USD_CACHE_MS",120000), solUsdStaleMs:num("SOL_USD_STALE_MS",300000), solUsdRefreshMs:num("SOL_USD_REFRESH_MS",45000), solUsdTimeoutMs:num("SOL_USD_TIMEOUT_MS",5000), solUsdLogIntervalMs:num("SOL_USD_LOG_INTERVAL_MS",300000),
  takeProfitPct:num("TAKE_PROFIT_PCT",30), hardStopLossPct:num("HARD_STOP_LOSS_PCT",12), softStopLossPct:num("SOFT_STOP_LOSS_PCT",8), trailingStopPct:num("TRAILING_STOP_PCT",8), profitProtectArmPct:num("PROFIT_PROTECT_ARM_PCT",15), flameTakeProfitPct:num("FLAME_TAKE_PROFIT_PCT",25), flameStopLossPct:num("FLAME_STOP_LOSS_PCT",12), flameProfitProtectArmPct:num("FLAME_PROFIT_PROTECT_ARM_PCT",12), flameTrailingStopPct:num("FLAME_TRAILING_STOP_PCT",6), executableQuoteDropPct:num("EXECUTABLE_QUOTE_DROP_PCT",20), minExecutableValueRatio:num("MIN_EXECUTABLE_VALUE_RATIO",0.65), rugExitPct:num("RUG_EXIT_PCT",45), maxPositionAgeMin:num("MAX_POSITION_AGE_MIN",12), positionPollMs:num("POSITION_POLL_MS",5000), positionStatusIntervalMs:num("POSITION_STATUS_INTERVAL_MS",5000), idlePositionStatusIntervalMs:num("IDLE_POSITION_STATUS_INTERVAL_MS",30000), reconcileIntervalMs:num("RECONCILE_INTERVAL_MS",30000), stateFile:process.env.STATE_FILE??"broke-dog-hybrid-state.json",
  axiomTrendingUrl:process.env.AXIOM_TRENDING_URL??"", axiomApiKey:process.env.AXIOM_TRENDING_API_KEY??"", fomoTrendingUrl:process.env.FOMO_TRENDING_URL??"", fomoApiKey:process.env.FOMO_TRENDING_API_KEY??"", bundleApiUrl:process.env.BUNDLE_API_URL??"", bundleApiKey:process.env.BUNDLE_API_KEY??"",
  xBearerToken:process.env.X_BEARER_TOKEN??"", socialPollMs:num("SOCIAL_POLL_MS",60000), socialTimeoutMs:num("SOCIAL_TIMEOUT_MS",8000), socialLookbackMin:num("SOCIAL_LOOKBACK_MIN",60), metaTopTerms:num("META_TOP_TERMS",8), smartMoneyCandidates:num("SMART_MONEY_CANDIDATES",2), smartMoneyMinScore:num("SMART_MONEY_MIN_SCORE",65), strongMomentumBuySellRatio:num("STRONG_MOMENTUM_BUY_SELL_RATIO",1.5), strongMomentumMinPrice5mPct:num("STRONG_MOMENTUM_MIN_PRICE_5M_PCT",-3)
};
export const SOL_MINT="So11111111111111111111111111111111111111112"; export const USDC_MINT="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"; export const LAMPORTS_PER_SOL=1_000_000_000;
