import { config } from "./config.ts";
import { enhancedTransactions,getHolderSnapshot,getMintInfo } from "./helius.ts";
import type { OnChainRiskSnapshot,RiskLevel } from "./types.ts";
import { log } from "./log.ts";
const pct=(n:number,d:number)=>d>0?n/d*100:0; const uniq=(xs:string[])=>[...new Set(xs.filter(Boolean))]; const asWallet=(x:any)=>typeof x==="string"&&x.length>=32?x:null;
function txActors(tx:any){const actors:string[]=[];if(asWallet(tx?.feePayer))actors.push(tx.feePayer);for(const a of tx?.accountData||[])if(a?.nativeBalanceChange<0&&asWallet(a.account))actors.push(a.account);for(const t of tx?.tokenTransfers||[]){if(asWallet(t?.fromUserAccount))actors.push(t.fromUserAccount);if(asWallet(t?.toUserAccount))actors.push(t.toUserAccount)}return uniq(actors)}
function detectLaunchClusters(txs:any[],mint:string,pairCreatedAt?:number){const createdSec=pairCreatedAt?Math.floor(pairCreatedAt/1000):null;const relevant=txs.filter(t=>!createdSec||!t.timestamp||Math.abs(Number(t.timestamp)-createdSec)<=config.launchWindowSeconds);const slots=new Map<number,string[]>(),actorCounts=new Map<string,number>(),tokenBuyers=new Set<string>();for(const tx of relevant){const actors=txActors(tx);for(const w of actors)actorCounts.set(w,(actorCounts.get(w)||0)+1);if(tx?.slot!=null){const arr=slots.get(tx.slot)||[];arr.push(...actors);slots.set(tx.slot,uniq(arr))}for(const tr of tx?.tokenTransfers||[]){if(tr?.mint!==mint)continue;const to=asWallet(tr?.toUserAccount);if(to)tokenBuyers.add(to)}}const crowdedSlots=[...slots.entries()].filter(([,ws])=>ws.length>=config.clusterWalletThreshold).map(([slot,wallets])=>({slot,wallets}));const repeatedActors=[...actorCounts.entries()].filter(([,count])=>count>=config.clusterRepeatThreshold).map(([wallet,count])=>({wallet,count})).sort((a,b)=>b.count-a.count);const clusterWallets=uniq(crowdedSlots.flatMap(x=>x.wallets));return{txCount:relevant.length,crowdedSlots,repeatedActors,clusterWallets,tokenBuyers:[...tokenBuyers]}}
async function sharedFunders(wallets:string[],launchTimeSec:number|null){const capped=uniq(wallets).slice(0,config.maxFundingWalletChecks);const map=new Map<string,string[]>();for(const wallet of capped){try{const txs=await enhancedTransactions(wallet,{limit:config.fundingHistoryLimit,sort:"desc",lteTime:launchTimeSec||undefined,gteTime:launchTimeSec?launchTimeSec-config.fundingLookbackSeconds:undefined,tokenAccounts:"none"});const funders=new Set<string>();for(const tx of txs)for(const tr of tx?.nativeTransfers||[])if(tr?.toUserAccount===wallet&&asWallet(tr?.fromUserAccount)&&Number(tr?.amount||0)>0)funders.add(tr.fromUserAccount);for(const f of funders){const arr=map.get(f)||[];arr.push(wallet);map.set(f,uniq(arr))}}catch{}}return[...map.entries()].filter(([,ws])=>ws.length>=2).map(([funder,wallets])=>({funder,wallets})).sort((a,b)=>b.wallets.length-a.wallets.length)}
export function classifyHolderRisk(snapshot:{totalSupply:number;holders:{owner:string;amount:number}[]}){const {totalSupply,holders}=snapshot;const top1=pct(holders[0]?.amount||0,totalSupply),top5=pct(holders.slice(0,5).reduce((s,h)=>s+h.amount,0),totalSupply),top10=pct(holders.slice(0,10).reduce((s,h)=>s+h.amount,0),totalSupply);let holderRisk:RiskLevel="low";if(top1>=config.holderTop1HighPct||top5>=config.holderTop5HighPct||top10>=config.holderTop10HighPct)holderRisk="high";else if(top1>=config.holderTop1MediumPct||top5>=config.holderTop5MediumPct||top10>=config.holderTop10MediumPct)holderRisk="medium";return{holderRisk,top1Pct:top1,top5Pct:top5,top10Pct:top10}}

const fastCache=new Map<string,{expires:number,value?:OnChainRiskSnapshot,promise?:Promise<OnChainRiskSnapshot>}>();
function withTimeout<T>(p:Promise<T>,ms:number,label:string):Promise<T>{return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`${label} timed out after ${ms}ms`)),ms);p.then(v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)})})}

// v1.4 PAPER FAST SAFETY: one quick, cached verification for the only things that
// should hard-veto a paper-learning entry: dangerous mint/freeze authority or
// extreme holder concentration. Deep launch/funder analysis remains available as
// enrichment, but it no longer stalls the paper trade decision.
export async function fastSafetyCheck(mint:string):Promise<OnChainRiskSnapshot>{
  const now=Date.now(),cached=fastCache.get(mint);
  if(cached?.value&&cached.expires>now)return cached.value;
  if(cached?.promise)return cached.promise;
  if(!config.heliusApiKey)return{checked:false,bundleRisk:"unknown",holderRisk:"unknown",devRisk:"unknown",confidence:"none",safetyMode:"fast",elapsedMs:0,notes:["HELIUS_API_KEY missing"]};
  const started=Date.now();
  const promise=withTimeout(Promise.all([getMintInfo(mint),getHolderSnapshot(mint)]),config.safetyTimeoutMs,"fast safety").then(([mintInfo,holders])=>{
    const holder=classifyHolderRisk(holders);let devRisk:RiskLevel="low";const notes:string[]=["fast safety verified"];
    if(mintInfo.freezeAuthority){devRisk="high";notes.push("freeze authority enabled")}
    if(mintInfo.mintAuthority){devRisk="high";notes.push("mint authority enabled")}
    if(!mintInfo.freezeAuthority&&!mintInfo.mintAuthority)notes.push("mint/freeze disabled");
    const value:OnChainRiskSnapshot={checked:true,bundleRisk:"unknown",holderRisk:holder.holderRisk,devRisk,confidence:"medium",top1Pct:holder.top1Pct,top5Pct:holder.top5Pct,top10Pct:holder.top10Pct,mintAuthority:mintInfo.mintAuthority,freezeAuthority:mintInfo.freezeAuthority,safetyMode:"fast",elapsedMs:Date.now()-started,notes};
    log.info(`🛡️ SAFETY VERIFIED in ${value.elapsedMs}ms | ${mint.slice(0,6)}… | dev:${devRisk} holders:${holder.holderRisk}`);
    fastCache.set(mint,{expires:Date.now()+config.safetyCacheMs,value});return value;
  }).catch(e=>{
    const value:OnChainRiskSnapshot={checked:false,bundleRisk:"unknown",holderRisk:"unknown",devRisk:"unknown",confidence:"error",safetyMode:"fast",elapsedMs:Date.now()-started,notes:[`fast safety incomplete: ${e instanceof Error?e.message:String(e)}`]};
    log.warn(`🛡️ SAFETY INCOMPLETE after ${value.elapsedMs}ms | ${mint.slice(0,6)}… | paper mode may continue for learning; live mode stays strict`);
    fastCache.set(mint,{expires:Date.now()+Math.min(config.safetyCacheMs,15_000),value});return value;
  }).finally(()=>{const x=fastCache.get(mint);if(x?.promise&&!x.value)fastCache.delete(mint)});
  fastCache.set(mint,{expires:now+config.safetyCacheMs,promise});
  return promise;
}

export async function analyzeRisk(mint:string,pairCreatedAt?:number):Promise<OnChainRiskSnapshot>{if(!config.heliusApiKey)return{checked:false,bundleRisk:"unknown",holderRisk:"unknown",devRisk:"unknown",confidence:"none",safetyMode:"deep",notes:["HELIUS_API_KEY missing"]};try{const started=Date.now();const [mintInfo,holders,launchTxs]=await Promise.all([getMintInfo(mint),getHolderSnapshot(mint),enhancedTransactions(mint,{limit:config.launchTxLimit,sort:"asc",tokenAccounts:"all"})]);const holder=classifyHolderRisk(holders),cluster=detectLaunchClusters(launchTxs,mint,pairCreatedAt),launchTimeSec=pairCreatedAt?Math.floor(pairCreatedAt/1000):(launchTxs[0]?.timestamp||null),shared=await sharedFunders(cluster.tokenBuyers.length?cluster.tokenBuyers:cluster.clusterWallets,launchTimeSec);const linkedWallets=uniq([...cluster.clusterWallets,...shared.flatMap(x=>x.wallets)]),linkedHeld=holders.holders.filter(h=>linkedWallets.includes(h.owner)).reduce((s,h)=>s+h.amount,0),estimatedLinkedSupplyPct=pct(linkedHeld,holders.totalSupply);let bundleRisk:RiskLevel="low";if(shared.some(x=>x.wallets.length>=config.sharedFunderHighWallets)||estimatedLinkedSupplyPct>=config.bundleSupplyHighPct||cluster.crowdedSlots.length>=config.crowdedSlotsHigh)bundleRisk="high";else if(shared.length||estimatedLinkedSupplyPct>=config.bundleSupplyMediumPct||cluster.crowdedSlots.length)bundleRisk="medium";let devRisk:RiskLevel="low";const notes:string[]=[];if(mintInfo.freezeAuthority){devRisk="high";notes.push("freeze authority enabled")}if(mintInfo.mintAuthority){devRisk="high";notes.push("mint authority enabled")}if(!mintInfo.freezeAuthority&&!mintInfo.mintAuthority)notes.push("mint/freeze disabled");if(shared.length)notes.push(`${shared.length} shared-funder cluster(s)`);if(cluster.crowdedSlots.length)notes.push(`${cluster.crowdedSlots.length} crowded launch slot(s)`);notes.push(`linked supply ${estimatedLinkedSupplyPct.toFixed(2)}%`);const enough=launchTxs.length>=config.minLaunchTxForConfidence;let confidence:"low"|"medium"|"high"=enough?"medium":"low";if(launchTxs.length>=30)confidence="high";if(!enough&&config.blockLowBundleConfidence)bundleRisk="unknown";return{checked:true,bundleRisk,holderRisk:holder.holderRisk,devRisk,confidence,estimatedLinkedSupplyPct,linkedWalletCount:linkedWallets.length,sharedFunderClusters:shared.length,crowdedLaunchSlots:cluster.crowdedSlots.length,top1Pct:holder.top1Pct,top5Pct:holder.top5Pct,top10Pct:holder.top10Pct,mintAuthority:mintInfo.mintAuthority,freezeAuthority:mintInfo.freezeAuthority,safetyMode:"deep",elapsedMs:Date.now()-started,notes}}catch(e){return{checked:true,bundleRisk:"unknown",holderRisk:"unknown",devRisk:"unknown",confidence:"error",safetyMode:"deep",notes:[`risk analysis failed: ${e instanceof Error?e.message:String(e)}`]}}}

export function paperRiskGate(r?:OnChainRiskSnapshot){
  if(r?.devRisk==="high")return{ok:false,why:"hard veto: mint/freeze authority risk"};
  if(r?.holderRisk==="high")return{ok:false,why:"hard veto: extreme holder concentration"};
  if(r?.bundleRisk==="high")return{ok:false,why:"hard veto: explicit high bundle/launch risk"};
  if(!r?.checked)return{ok:true,why:"paper learning: safety incomplete, no hard-danger evidence"};
  return{ok:true,why:"fast paper safety approved"};
}
export function normalRiskGate(r?:OnChainRiskSnapshot){if(!r?.checked)return{ok:false,why:"on-chain risk not verified"};if(r.bundleRisk==="unknown")return{ok:false,why:"bundle/launch risk unverified"};if(r.bundleRisk==="high")return{ok:false,why:"high bundle/launch risk"};if(r.devRisk==="high")return{ok:false,why:"high dev authority risk"};if(r.holderRisk==="high")return{ok:false,why:"high holder concentration"};return{ok:true,why:"risk approved"}}
export function flameRiskGate(r?:OnChainRiskSnapshot){if(r?.devRisk==="high")return{ok:false,why:"hard veto: mint/freeze authority risk"};if(r?.holderRisk==="high")return{ok:false,why:"hard veto: extreme holder concentration"};if(r?.bundleRisk==="high")return{ok:false,why:"hard veto: high launch/bundle risk"};return{ok:true,why:r?.checked?"calculated-risk flame allowed":"risk incomplete; flame exception allowed"}}
