export type FeedSource = "birdeye-new" | "birdeye-trending" | "birdeye-meme" | "dex-profile" | "dex-boost" | "dex-boost-top" | "dex-momentum" | "mobula-axiom-volume" | "mobula-axiom-price" | "axiom" | "fomo" | "social-watchlist";
export type EntryLane = "NORMAL" | "ELITE" | "FLAME";
export type MicroCycleState = "DEAD"|"WAKING"|"BUILDING"|"BREAKOUT"|"RUNNING"|"EXHAUSTING"|"REVERSING";
export interface MicroCycleAnalysis { state:MicroCycleState; score:number; runnerProbability:number; lateEntryRisk:number; exhaustionRisk:number; scoreVelocity:number; scoreAcceleration:number; buyerAccelerationPct:number; volumeAccelerationPct:number; priceVelocityPct:number; buySellRatio:number; moneyFlowRatio:number; structureBreak:boolean; higherLow:boolean; antiFomoBlocked:boolean; adjustment:number; reasons:string[]; }
export interface TradeEntryAnalysis { score:number; runnerScore?:number; qualityScore?:number; confidence:number; marketScore?:number; socialScore?:number; safetyScore?:number; microCycle?:MicroCycleAnalysis; liquidityUsd?:number; marketCapUsd?:number; holderCount?:number; uniqueWallet1m?:number; volume1mUsd?:number; volume5mUsd?:number; buys1m?:number; sells1m?:number; buyVolume1mUsd?:number; sellVolume1mUsd?:number; priceChange1mPct?:number; priceChange5mPct?:number; top1Pct?:number; top5Pct?:number; top10Pct?:number; bundleRisk?:RiskLevel; holderRisk?:RiskLevel; devRisk?:RiskLevel; linkedSupplyPct?:number; smartMoneyScore?:number; socialAccounts?:string[]; dominantMeta?:string[]; metaRunner?:boolean; sources:string[]; tokenAgeMin:number; routeQuality?:number; buyRoute:boolean; sellRoute:boolean; routeQuotedAt?:number; routeRoundTripPct?:number; routeRouter?:string; routeMode?:string; routeFeeBps?:number; sourceFirstSeenAt?:Record<string,number>; firstBuyScoreAt?:number; decisionAt?:number; missingFields?:string[]; }
export type RiskLevel = "low" | "medium" | "high" | "unknown";
export interface DiscoveredToken { address:string; name:string; symbol:string; decimals?:number; source:FeedSource; rank?:number; discoveredAt:number; listedAt?:number; seed?:Partial<Snapshot>; }
export interface SocialIntelSnapshot { enabled:boolean; score:number; mentions:number; weightedMentions:number; keyAccounts:string[]; pumpFun:boolean; metaMatch:boolean; dominantMeta:string[]; }
export interface SmartMoneySnapshot { checked:boolean; smartTraders:number; snipers:number; insiders:number; bundlers:number; devs:number; score:number; }
export interface OnChainRiskSnapshot { checked:boolean; bundleRisk:RiskLevel; holderRisk:RiskLevel; devRisk:RiskLevel; confidence:"none"|"low"|"medium"|"high"|"error"; top1Pct?:number; top5Pct?:number; top10Pct?:number; estimatedLinkedSupplyPct?:number; linkedWalletCount?:number; sharedFunderClusters?:number; crowdedLaunchSlots?:number; mintAuthority?:string|null; freezeAuthority?:string|null; safetyMode?:"fast"|"deep"; elapsedMs?:number; notes:string[]; }
export interface Snapshot { at:number; priceUsd?:number; liquidityUsd?:number; marketCapUsd?:number; holderCount?:number; volume1mUsd?:number; volume5mUsd?:number; volume1hUsd?:number; buys1m?:number; sells1m?:number; buys5m?:number; sells5m?:number; trades1m?:number; uniqueWallet1m?:number; buyVolume1mUsd?:number; sellVolume1mUsd?:number; priceChange1mPct?:number; priceChange5mPct?:number; top10HolderPct?:number; bundleRisk?:number; bundleStatus:"ok"|"unknown"|"pending"|"error"|"skipped"; buyRoute:boolean; sellRoute:boolean; routeQuality?:number; routeQuotedAt?:number; routeRoundTripPct?:number; routeRouter?:string; routeMode?:string; routeFeeBps?:number; dexPairAddress?:string; dexId?:string; social?:SocialIntelSnapshot; smartMoney?:SmartMoneySnapshot; onChainRisk?:OnChainRiskSnapshot; dataErrors?:string[]; }
export interface Candidate { token:DiscoveredToken; firstSeenAt:number; lastSeenAt:number; sources:Set<FeedSource>; sourceFirstSeenAt?:Partial<Record<FeedSource,number>>; firstBuyScoreAt?:number; trendingRanks:Partial<Record<FeedSource,number>>; previousTrendingRanks?:Partial<Record<FeedSource,number>>; rankMovement?:Partial<Record<FeedSource,number>>; snapshots:Snapshot[]; score:number; runnerScore?:number; qualityScore?:number; dataConfidence:number; state:"WATCHING"|"DEVELOPING"|"READY"|"BOUGHT"|"DROPPED"|"FAILED"; decisionReason?:string; marketScore?:number; socialScore?:number; safetyScore?:number; metaRunner?:boolean; entryLane?:EntryLane; collecting:boolean; lastDroppedAt?:number; watchCycles?:number; microCycle?:MicroCycleAnalysis; scoreHistory?:{at:number;score:number}[]; }
export interface Position { mint:string; priceHistory?:{at:number;priceUsd:number;pnlPct:number}[]; runnerMode?:"STANDARD"|"STRONG_RUNNER"|"MONSTER_RUNNER"; runnerConfidence?:number; runnerLastLogAt?:number; name:string; symbol:string; decimals:number; tokenAmountRaw:bigint; entrySolLamports:bigint; entryUsd:number; entryPriceUsd:number; openedAt:number; highPriceUsd:number; highExecutablePnlPct?:number; lastExecutablePnlPct?:number; peakProtectionArmedAt?:number; lastExecutableUsd?:number; lastExecutableQuoteAt?:number; signature?:string; scoreAtBuy?:number; confidenceAtBuy?:number; paper?:boolean; socialAccountsAtBuy?:string[]; metaRunnerAtBuy?:boolean; lane?:EntryLane; basisUnknown?:boolean; paperEntryCostUsd?:number; entryAnalysis?:TradeEntryAnalysis; }
export interface SwapOrder { transaction:string|null; requestId:string; inAmount?:string; outAmount:string; router?:string; mode?:string; feeBps?:number; feeMint?:string; errorCode?:number; errorMessage?:string; }
